---
name: CD

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  deliver:
    name: Build and Test
    uses: neticdk/shared-github-actions/.github/workflows/go-cd.yaml@main
    secrets: inherit
