---
name: release

on:
  workflow_dispatch:
  release:
    types: [created]
  workflow_call:

permissions:
  contents: write
  packages: write

jobs:
  release-matrix:
    name: Release go binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Set PATH
        run: echo "$(go env GOPATH)/bin" >> $GITHUB_PATH

      - name: Install Go Releaser
        uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
