---
name: CD

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    uses: neticdk/shared-github-actions/.github/workflows/go-cd.yaml@v0.4.2
    secrets: inherit
