---
name: CD

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  packages: write

jobs:
  release:
    name: Release
    uses: neticdk/shared-github-actions/.github/workflows/go-cd.yaml@f359d25deda20bf8899c152897637f9094055562 # main
    secrets: inherit
